Game
SDL_Window* Game::window
SDL_GLContext Game::context
Cube Game::cube[5][5][5][5]
Game::Game()
Game::~Game()
bool Game::init()
Initialise SDL so it's setup for OpenGL.true if everything initiated okay, false otherwise
Referenced by main.
bool Game::objectInit()
Initialise GLEW and then initialise any game entities.true if everything initiated okay, false otherwise
References Cube::setPos, Cube::setType, Cube::createCube.
Referenced by main.
bool Game::createWindow(const char *, int, int)
Create an SDL window that's setup for OpenGL. title - The window title width - Window width height - Window height true if everything initiated okay, false otherwise
Referenced by main.
bool Game::createContext()
Create an OpenGL context then bind it to the window.true if everything created okay, false otherwise
Referenced by main.
bool Game::handleEvents(SDL_Event)
Empty method setup to easily handle events.true if everything handled okay, false otherwise
Referenced by main.
bool Game::update()
Games update method.true if everything update successful, false otherwise
References Cube::update.
Referenced by main.
bool Game::render()
Games render method.
References Cube::draw.
Referenced by main.
void Game::swapBuffers()
Swap out the openGL buffer to be called at every tick.
Referenced by main.