Cube
Type
Shader* Cube::shader
GLuint Cube::shaderProgram
GLuint Cube::fragmentShader
GLuint Cube::vertexShader
GLuint Cube::vao
GLuint Cube::vbo
GLuint Cube::ebo
GLfloat Cube::x
GLfloat Cube::y
GLfloat Cube::z
GLfloat Cube::r
GLfloat Cube::g
GLfloat Cube::b
GLint Cube::uniTrans
glm::mat4 Cube::trans
Cube::Cube()
Cube::~Cube()
void Cube::setPos(GLfloat X, GLfloat Y, GLfloat Z)
A simple setter for the Cubes positions. X, Y & Z are the cubes world positions.
Referenced by Game::objectInit.
void Cube::setType(Type)
Setter to set type of cube. Type is an Enum.
Referenced by Game::objectInit.
void Cube::createProgram()
void Cube::createCube()
Creates the actual cube.
Referenced by Game::objectInit.
void Cube::update()
Referenced by Game::update.
void Cube::draw()
Referenced by Game::render.
void Cube::createShader()