.TH "src/global.h" 3 "Thu Jan 8 2015" "Version v0.1" "Voxel Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/global.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GL/glew\&.h>\fP
.br
\fC#include <SDL2/SDL\&.h>\fP
.br
\fC#include <SDL2/SDL_opengl\&.h>\fP
.br
\fC#include 'shader\&.h'\fP
.br
\fC#include <glm/glm\&.hpp>\fP
.br
\fC#include <glm/gtc/matrix_transform\&.hpp>\fP
.br
\fC#include <glm/gtc/type_ptr\&.hpp>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLEW_STATIC\fP"
.br
.ti -1c
.RI "#define \fBGLM_FORCE_RADIANS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLEW_STATIC"

.PP
Definition at line 11 of file global\&.h\&.
.SS "#define GLM_FORCE_RADIANS"

.PP
Definition at line 18 of file global\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Voxel Game from the source code\&.
