.TH "src/main.cpp" 3 "Thu Jan 8 2015" "Version v0.1" "Voxel Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'game\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBwidth\fP = 800"
.br
.ti -1c
.RI "int \fBheight\fP = 600"
.br
.ti -1c
.RI "const char * \fBtitle\fP = 'OpenGL Test'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 17 of file main\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int height = 600"

.PP
Definition at line 14 of file main\&.cpp\&.
.SS "const char* title = 'OpenGL Test'"

.PP
Definition at line 15 of file main\&.cpp\&.
.SS "int width = 800"

.PP
Definition at line 13 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Voxel Game from the source code\&.
