.TH "src/shader.cpp" 3 "Thu Jan 8 2015" "Version v0.1" "Voxel Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/shader.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'shader\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Voxel Game from the source code\&.
